### ISSUE TITLE
Win32 Install Error

### ISSUE THREAD

**Issue by philipathomas** [fgimian/easysnmp#32] opened 2015-08-31 18:56 UTC
Hi All, 

Stumbled on a install problem on windows 7 which I'm guessing has something to do with the native windows compiler but google search does not seem to have a fix. Install output bellow, any suggestions on how to fix this is appreciated. Thanks, Phil

C:\scripts\GIT\easysnmp>python setup.py install
'net-snmp-config' is not recognized as an internal or external command,
operable program or batch file.
C:\Python34\lib\site-packages\setuptools-18.2-py3.4.egg\setuptools\dist.py:285: UserWarning: Normalizing '0.2.5-dev' to '0.2.5.dev
0'
running install
running bdist_egg
running egg_info
creating easysnmp.egg-info
writing dependency_links to easysnmp.egg-info\dependency_links.txt
writing top-level names to easysnmp.egg-info\top_level.txt
writing easysnmp.egg-info\PKG-INFO
writing manifest file 'easysnmp.egg-info\SOURCES.txt'
reading manifest file 'easysnmp.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'easysnmp.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib.win32-3.4
creating build\lib.win32-3.4\easysnmp
copying easysnmp\compat.py -> build\lib.win32-3.4\easysnmp
copying easysnmp\easy.py -> build\lib.win32-3.4\easysnmp
copying easysnmp\exceptions.py -> build\lib.win32-3.4\easysnmp
copying easysnmp\helpers.py -> build\lib.win32-3.4\easysnmp
copying easysnmp\session.py -> build\lib.win32-3.4\easysnmp
copying easysnmp\utils.py -> build\lib.win32-3.4\easysnmp
copying easysnmp\variables.py -> build\lib.win32-3.4\easysnmp
copying easysnmp\__init__.py -> build\lib.win32-3.4\easysnmp
running build_ext
building 'easysnmp.interface' extension
creating build\temp.win32-3.4
creating build\temp.win32-3.4\Release
creating build\temp.win32-3.4\Release\easysnmp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python34\include -IC:\
Python34\include /Tceasysnmp/interface.c /Fobuild\temp.win32-3.4\Release\easysnmp/interface.obj -Wno-unused-function
cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\cl.exe' failed with exit status 2

C:\scripts\GIT\easysnmp>python setup.py build
'net-snmp-config' is not recognized as an internal or external command,
operable program or batch file.
C:\Python34\lib\site-packages\setuptools-18.2-py3.4.egg\setuptools\dist.py:285: UserWarning: Normalizing '0.2.5-dev' to '0.2.5.dev
0'
running build
running build_py
running build_ext
building 'easysnmp.interface' extension
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python34\include -IC:\
Python34\include /Tceasysnmp/interface.c /Fobuild\temp.win32-3.4\Release\easysnmp/interface.obj -Wno-unused-function
**cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'**
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\cl.exe' failed with exit status 2

**Comment by nnathan** [comment] 2015-08-31 23:20
I've never tried to compile in Win32, but I think this is an obvious incompatibility in the arguments passed to the compiler. I think this can be rectified in the `setup.py` by changing [this line](https://github.com/fgimian/easysnmp/blob/master/setup.py#L11) to read `compiler_args=[]`.

If you manage to get it to work in Win32, I'll be happy to patch the setup.py to add Win32 conditionals.

**Comment by fgimian** [comment] 2016-02-29 03:17
Yep, as Naveen mentioned, I really don't think we can target Windows as a compatible platform for this library.  It really was designed and tested on Linux only.

As such, I will be closing this case.

Cheers
Fotis

**Closed by fgimian** 2016-02-29 03:17 UTC

**Comment by kamakazikamikaze** [comment] 2016-04-11 05:37
I've actually been playing around with trying to make this compile on Windows today. I've made a little (if truly any) progress. I didn't realize how truly terrible/rusty I am with C/C++ until I spent the last few hours working with errors.

Thus far I have:
* Omit `'-Wno-unused-function'` if the platform is `win32`
* Converted GCC flags for `--debug` to potentially Windows-equivalent ones
  * `-Wall` => `/Wall`
  * `-O0` => `/Od`
  * `-g` => `/Zi`
* Browse the registry for the `Net-SNMP` key to retrieve the base directory
* Potentially identified the correct `libs` values to pass

This, of course, opened up a whole can of worms with cross-platform compatibility. So in `interfaces.c` I've had to add:

    #ifdef _MSC_VER

    typedef __int32 int32_t;
    typedef unsigned __int32 uint32_t;
    typedef __int64 int64_t;
    typedef unsigned __int64 uint64_t;
    typedef int mode_t;

    #else
    #include <stdint.h>
    #endif
    // I could probably merge these two, but I can clean that up later
    #ifdef _WIN32
    #include <winsock2.h>
    #else
    #include <arpa/inet.h>
    #include <netdb.h>
    #endif

Now I'm just encountering an issue with some enumerators, specifically:
`. . .\easysnmp\easysnmp\interface.c(107) : error C2059: syntax error : 'constant'`
which points to:
`enum { INFO, WARNING, ERROR, DEBUG, EXCEPTION };`

I don't see any of these being predefined macros in VS 2010. I suppose it could be `ERROR` because I later see:
`\easysnmp\easysnmp\interface.c(2789) : error C2065: 'DEBUG' : undeclared identifier`
`\easysnmp\easysnmp\interface.c(3624) : error C2065: 'EXCEPTION' : undeclared identifier`

I guess I should open this up as a Visual Studio project to get more details,

**Comment by kamakazikamikaze** [comment] 2016-04-11 06:04
Ok, it's definitely `ERROR`. I'm assuming that it's supposed to work since it's coming from `net-snmp/net-snmp-includes.h`?

**Comment by karthhic** [comment] 2016-07-28 07:46
Hi guys i am having the same issue but in linux...

linuxlite@linuxlite-virtual-machine:~$ python -m pip install easysnmp
Collecting easysnmp
  Using cached easysnmp-0.2.4.tar.gz
Building wheels for collected packages: easysnmp
  Running setup.py bdist_wheel for easysnmp ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eLBVFV/easysnmp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpQUMEFHpip-wheel- --python-tag cp27:
  sh: 1: net-snmp-config: not found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/easysnmp
  copying easysnmp/exceptions.py -> build/lib.linux-x86_64-2.7/easysnmp
  copying easysnmp/utils.py -> build/lib.linux-x86_64-2.7/easysnmp
  copying easysnmp/easy.py -> build/lib.linux-x86_64-2.7/easysnmp
  copying easysnmp/helpers.py -> build/lib.linux-x86_64-2.7/easysnmp
  copying easysnmp/compat.py -> build/lib.linux-x86_64-2.7/easysnmp
  copying easysnmp/variables.py -> build/lib.linux-x86_64-2.7/easysnmp
  copying easysnmp/session.py -> build/lib.linux-x86_64-2.7/easysnmp
  copying easysnmp/__init__.py -> build/lib.linux-x86_64-2.7/easysnmp
  running build_ext
  building 'easysnmp.interface' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/easysnmp
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c easysnmp/interface.c -o build/temp.linux-x86_64-2.7/easysnmp/interface.o -Wno-unused-function
  easysnmp/interface.c:3:38: fatal error: net-snmp/net-snmp-config.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for easysnmp
  Running setup.py clean for easysnmp
Failed to build easysnmp
Installing collected packages: easysnmp
  Running setup.py install for easysnmp ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eLBVFV/easysnmp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-x2KKJV-record/install-record.txt --single-version-externally-managed --compile:
    sh: 1: net-snmp-config: not found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/easysnmp
    copying easysnmp/exceptions.py -> build/lib.linux-x86_64-2.7/easysnmp
    copying easysnmp/utils.py -> build/lib.linux-x86_64-2.7/easysnmp
    copying easysnmp/easy.py -> build/lib.linux-x86_64-2.7/easysnmp
    copying easysnmp/helpers.py -> build/lib.linux-x86_64-2.7/easysnmp
    copying easysnmp/compat.py -> build/lib.linux-x86_64-2.7/easysnmp
    copying easysnmp/variables.py -> build/lib.linux-x86_64-2.7/easysnmp
    copying easysnmp/session.py -> build/lib.linux-x86_64-2.7/easysnmp
    copying easysnmp/__init__.py -> build/lib.linux-x86_64-2.7/easysnmp
    running build_ext
    building 'easysnmp.interface' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/easysnmp
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c easysnmp/interface.c -o build/temp.linux-x86_64-2.7/easysnmp/interface.o -Wno-unused-function
    easysnmp/interface.c:3:38: fatal error: net-snmp/net-snmp-config.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eLBVFV/easysnmp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-x2KKJV-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-eLBVFV/easysnmp/
